import Head from 'next/head';
import Feed from '../components/Feed';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Modal from '../components/Modal';

export default function Home() {
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>Instagram clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Feed />
      <Modal />
      <Footer/>
    </div>
  );
}
